name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./mvnw package
    - name: Publish
      # Don't publish for builds triggered by pull requests (pull requests from forks won't have access to secrets anyway)
      if: github.event_name != 'pull_request'
      env:
        BINTRAY_USER: ${{secrets.BINTRAY_USER}}
        BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
        S3_REPO_DEPLOY_URL: ${{secrets.S3_REPO_DEPLOY_URL}}
        S3_REPO_AWS_ACCESS_KEY: ${{secrets.S3_REPO_AWS_ACCESS_KEY}}
        S3_REPO_AWS_SECRET_ACCESS_KEY: ${{secrets.S3_REPO_AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: ${{secrets.AWS_REGION}}
      run: ./deploy-artifact.sh
